# This is a basic workflow to help you get started with Actions

# 액션 이름
name: Hello World

# Controls when the workflow will run
# Actions : Event 기반
# Commit을 main branch에 push / pull_request 했을 때 작동
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows 참고하자
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# -----------------------------------------------------
# push가 일어났을 때, 아래와 같은 일들이 일어난다
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls-al
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
